language: php

php:
- '7.1'
env:
  global:
  - ZIP_FILENAME=temporary-closures-bmlt-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
  - S3_BUCKET=archives.bmlt.app
  - S3_KEY=temporary-closures-bmlt
jobs:
  include:

  - stage: lint
    install:
    - composer install
    script:
    - find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
    - vendor/squizlabs/php_codesniffer/bin/phpcs --warning-severity=6 --standard=PSR2 --ignore=vendor --extensions=php --report=summary ./
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_S3=dist/s3
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=temporary-closures-bmlt.zip
    - PLUGIN="temporary-closures-bmlt"
    - MAINFILE="temporary-closures.php"
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*" -x "*assets*" -x "*vendor*" -x "composer.*" -x "*.gitattributes" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    - curl -LO https://raw.githubusercontent.com/bmlt-enabled/bmlt-wordpress-deploy/master/deploy-wordpress.sh
    - chmod +x deploy-wordpress.sh
    deploy:
    - provider: s3
      access_key_id: AKIAI7JHYFA6DI3WYP5A
      secret_access_key:
        secure: 5ctNdk0SdPsVg8DglqBBJxso0cKqtfRYgBkizK+0KysLFbAzHL3ZlwaODl8hcKSicYz5isuRSsQFQ1/kl24PFayHK52tsExKxyGjQJKQoiAzaEzTumAArto1U7EOVQPvk/g9Z0z2J99QQL9WOrXbPeYlWPEs7jOq31kIw818tEz8H3fyWR0k+/VgTO7D+3JuFUe7Tk4+QsQF/m1bYD4+HsuQ2Baew9OgEvpnHWCZavsZijqYkzpab2rjba4ogVVOBp37Ckntn3C8SI3Dka4iv4ya1w/5KdX6zxaQKenmF++l2SkM78QIKjEC949vSo2Z7QPYym9ZhXHWcyf4HH0B/D102LLtFPdR+he+fW/ZhcelvCb+SY6oPK4gJlxU3hIvn9GhNIimTZGVAeSivGDqt6YC7PnMLUHSLTlShMcta0NNLXS2rclnz936fFdJfwfdgB13fHdkoojO3k2XGPRXqwF1hLbkzo+j0/xUwaHBG/U0AGQigfL5xgLHX7vWI4gvaMvkIUGYpgAs7E+b8X0d2PUU5QMSzBRBmRRUAFKqoRhr/eh0ADkftccZN+lODzmwsmL8K2NBCGJSdvWy+xD9y/iVR9Cu35A69ysDGKX6mnIExxenfoGb98+NZBQla00kmNMAtbwLh5TzE8FlA2vNz8o8AcKtUbAJMhyoa8zzg3k=
      bucket: "$S3_BUCKET"
      local_dir: "$DIST_DIR_S3"
      upload-dir: "$S3_KEY"
      skip_cleanup: true
      on:
        all_branches: true
    - provider: releases
      api_key:
        secure: omNShqzlR9/OGaTS9uR4uE8rRuc5F1AVL+7wfQmeLfRj/EPpHvCaj/8Hdy8gwwex3eKUm+m/+Uf007rtCGyHtchF/Zme/KUpoA2/BAAvwmXtlr57sngOQTsnOhO0Ilhka3kV/qxcW52akiJ9XcUtWyWVfUDu6+QoIm2ehE2BcdjH7B4v7oTcOl+6j/EVaBGTu6WO992tvBJfwAyVmo7SPnUMh683aHfQdpofcpjKeQtUPJ2Ew0l/Zdk0R2wsNOAEwYGguUd/LuN1G+FNbk5DrW1Ybw4mRJanojvewSQAqQ5wnInLQQIFfyC/qj1gXAHzAi7Tv2O41PRR3c0V98GEY9srMOfgI/Q9nBl5kylNZjnc7C7hvyUusjk0jJjxVskYviqPgOIrj/2URUYqvCVfjpMnAKpfnwU5gIgTj8pUdrBTrdN9dI4yM7AXQy6AX8EF+cn2QDSfDBtr0BMYyQrVir2JU85HZZiWFs6NbwZtpJKLIicHuDHPpTZyWbSb4WWF8+BQNmRUjfMg8kesFbk58jwLBtAnPLTdMC40QAakdhKlqi/EGlZPY6XCDr8lagi1NOIrYJYj5186QgbFMN62TTq1frLHJN/Bc2cFfp54WhKQ6N4tX6plEco8jbW7DUVWmriNnf5kiTU7q5OZmMd1QEt0qejMsm8Dijci+pHKw4Y=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      on:
        tags: true
        condition: $TRAVIS_TAG != *beta*
    - provider: releases
      api_key:
        secure: omNShqzlR9/OGaTS9uR4uE8rRuc5F1AVL+7wfQmeLfRj/EPpHvCaj/8Hdy8gwwex3eKUm+m/+Uf007rtCGyHtchF/Zme/KUpoA2/BAAvwmXtlr57sngOQTsnOhO0Ilhka3kV/qxcW52akiJ9XcUtWyWVfUDu6+QoIm2ehE2BcdjH7B4v7oTcOl+6j/EVaBGTu6WO992tvBJfwAyVmo7SPnUMh683aHfQdpofcpjKeQtUPJ2Ew0l/Zdk0R2wsNOAEwYGguUd/LuN1G+FNbk5DrW1Ybw4mRJanojvewSQAqQ5wnInLQQIFfyC/qj1gXAHzAi7Tv2O41PRR3c0V98GEY9srMOfgI/Q9nBl5kylNZjnc7C7hvyUusjk0jJjxVskYviqPgOIrj/2URUYqvCVfjpMnAKpfnwU5gIgTj8pUdrBTrdN9dI4yM7AXQy6AX8EF+cn2QDSfDBtr0BMYyQrVir2JU85HZZiWFs6NbwZtpJKLIicHuDHPpTZyWbSb4WWF8+BQNmRUjfMg8kesFbk58jwLBtAnPLTdMC40QAakdhKlqi/EGlZPY6XCDr8lagi1NOIrYJYj5186QgbFMN62TTq1frLHJN/Bc2cFfp54WhKQ6N4tX6plEco8jbW7DUVWmriNnf5kiTU7q5OZmMd1QEt0qejMsm8Dijci+pHKw4Y=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      prerelease: true
      on:
        tags: true
        condition: $TRAVIS_TAG =~ "beta"
    - provider: script
      script: ./deploy-wordpress.sh
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    rooms:
    - secure: bmoIugz9sorNakDw7LnfC3iB7a4CnhuZeZBAVxefSoqipbZAGLoA86pSaDwSK3kNsCRAUXyHJ0pBxxJuCO5jrQKhl9TNBFQQ60KPvn3LQj9OXXTSHp4qoqBytipQGyjeqySu4fJt8Lc0u8FQ0qinxn21qF7K7c54aygVKQd+nxf/+9rVzSOJIY+c6UEBb9FwKfHl9cOJy8nTHYPNl0ZbQaYVS1gvyOV2jzrlurOXb0t2xYs2W9EOAjUd2E4ZVaD8EEyRZ9zcvy8ne41qZGBLMJjHZo6TdN4x0AdEYiITst5fKj+YILNCaVQMyURu5h65RPVXyjZ/eIOUixSt1EOpMTxWcRiDn3H7B2F7eEUIXyo/c5x1AEWEQFLGK+/PEqWx/zaBG0rJJdzVbLaqet2kg5piy+f84EBCZiXm7CZIYPMSjLJo9AJDcY9iSRgvpRnkSagHZAgMILNut53aNPd8i3FoOeycPwux/KDQpSz0uIpn4xu26VY0bzxJ8N27VugUhmNhLCN05Hgw8GoDjEoh4EgPPsdNVzXT4mzpjx2GfhRZOm/78LUSDB/w3oIAEPzRFfhberBAo0l2w9T5+Ynbw9yyquYgNUOW/nMhbwqOPbWqndHa8Xume0DXp2COHEqoSZx4gDIIRRKjKdsrFjjasWB5K7IQXQfBoiGAL7EscNA=
    on_success: change
  email: false

