version: '3.1'

services:
  wordpress:
    build: .
    restart: always
    ports:
      - 8081:80
      - 4443:443
    environment:
      WORDPRESS_DB_PASSWORD: example
      VIRTUAL_HOST: localhost
    volumes:
      - ../:/var/www/html/wp-content/plugins
      - ./logs/:/var/log/apache2

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
